### ISSUE TITLE
钉钉打卡提示版本过低，能更新最新版吗

### ISSUE THREAD

**Issue by leehoupeng** [SmileZXLee/CrackediOSApps#3]
钉钉4.5.15打卡提示版本过低，管理员端提示尝试使用低版本钉钉打卡，已开启人脸验证，可以更新一下新版本吗

**Comment by SmileZXLee** [comment]
已更新至最新版本V4.6.34，您可以重新下载再次尝试一下。

**Comment by leehoupeng** [comment]
> 已更新至最新版本V4.6.34，您可以重新下载再次尝试一下。

可安装，打开助手后返回定位打卡页面无法加载。

**Comment by EchoYao** [comment]
的确提示版本过低，必须使用人脸才能打卡。可否给4.6.37的！

**Comment by leehoupeng** [comment]
4.6.36可以打卡，但是因为之前的34版本不行，下载了appstore里的37版本，每次都需要人脸，能否麻烦大神升级一下，另外提醒后来的小伙伴们，不要升级钉钉，高版本有记录。

**Comment by SmileZXLee** [comment]
> 的确提示版本过低，必须使用人脸才能打卡。可否给4.6.37的！

感谢您的反馈，新版本已更新，重新下载即可

**Comment by SmileZXLee** [comment]
> 4.6.36可以打卡，但是因为之前的34版本不行，下载了appstore里的37版本，每次都需要人脸，能否麻烦大神升级一下，另外提醒后来的小伙伴们，不要升级钉钉，高版本有记录。

感谢您的反馈，新版本已更新，重新下载即可

**Comment by leehoupeng** [comment]
已解决，完美可用。
